rcu: Use correct rcu_state for trace_rcu_exp_grace_period
In file included from ../kernel/rcu/tree.c:4309:
../kernel/rcu/tree_exp.h:600:29: error: use of undeclared identifier 'rcu_state'; did you mean 'rcu_bh_state'?
  600 |         trace_rcu_exp_grace_period(rcu_state.name, s, TPS("end"));
      |                                    ^~~~~~~~~
      |                                    rcu_bh_state
../kernel/rcu/tree.c:118:1: note: 'rcu_bh_state' declared here
  118 | RCU_STATE_INITIALIZER(rcu_bh, 'b', call_rcu_bh);
      | ^
../kernel/rcu/tree.c:103:18: note: expanded from macro 'RCU_STATE_INITIALIZER'
  103 | struct rcu_state sname##_state = { \
      |                  ^
<scratch space>:76:1: note: expanded from here
   76 | rcu_bh_state
      | ^
1 error generated.

Fixes: beb2ec8fe84ffae8eb93aaaf0f7f1eb038a50c6f ("rcu: Allow only one expedited GP to run concurrently with wakeups")
Signed-off-by: Vayruz Rafli <vayruzrafli79@outlook.co.id>